### ISSUE TITLE
Cannot declare nested routes

### ISSUE THREAD

**Issue by jaysson** [fenok/react-router-typesafe-routes#19] opened 2022-11-17 06:55 UTC
```ts
const routes = {
	root: route('', {}, { auth: route('auth', {}) }),
};
```

Throws

```ts
Argument of type '{ auth: RouteWithChildren<void, "auth", Record<never, never>, Record<never, never>, never[], Record<never, never>>; }' is not assignable to parameter of type 'undefined'.
```
I am using typescript 4.9.4.

**Comment by fenok** [comment] 2022-11-19 11:56
Hello! This is actually intentional. You're hitting a safeguard that prevents child routes from starting with a lowercase character. Granted, it's a bit confusing, but I'm not sure how to make the error message more user-friendly.

Quoting from the README (grammatical error fixed):

> Child routes have to be in CONSTANT_CASE or PascalCase to prevent overlapping with other route fields.

As stated, the reason for this is to prevent clashing between child routes and (current and future) route API (such as `path`, `buildUrl`, `types`, etc.).

I also run tests for typescript v4.9.3, which seems to be the latest at the moment, and can confirm that everything works fine.

**Comment by fenok** [comment] 2022-12-14 18:52
I'm closing this because it seems to work as intended. I mentioned this quirk in the "Limitations" section in README.

Please reopen if I'm missing something.

**Closed by fenok** 2022-12-14 18:52 UTC

**Comment by fenok** [comment] 2023-04-07 16:07
Addressed in https://github.com/fenok/react-router-typesafe-routes/pull/31
